# Generated by Django 4.2.2 on 2023-06-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ongs',
            new_name='Ong',
        ),
        migrations.RenameModel(
            old_name='Voluntarios',
            new_name='Voluntario',
        ),
        migrations.RenameField(
            model_name='voluntario',
            old_name='ongs',
            new_name='ong',
        ),
    ]
