# Generated by Django 4.2.2 on 2023-06-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_ong_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='ong',
            field=models.ForeignKey(db_column='teste', on_delete=django.db.models.deletion.CASCADE, to='back.ong'),
        ),
    ]
