# Generated by Django 4.2.2 on 2023-06-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_voluntario_ong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teste', to='back.ong'),
        ),
    ]
