# Generated by Django 4.2.2 on 2023-06-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_alter_voluntario_ong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.ong'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.ong')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=80)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.ong')),
            ],
        ),
    ]
