# Generated by Django 4.2.2 on 2023-06-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='senha',
        ),
    ]
