# Generated by Django 4.2.2 on 2023-06-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_rename_password_user_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
