# Generated by Django 4.2.2 on 2023-06-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_user_email_alter_user_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
