# Generated by Django 4.2.1 on 2023-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
