# Generated by Django 4.2.1 on 2023-06-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
